//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.DSXUpdates {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DSXUpdateRequest", Namespace="http://Bank.Service.DSXUpdate/")]
    [System.SerializableAttribute()]
    public partial class DSXUpdateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentUDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BufferIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompletionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentUDI {
            get {
                return this.DocumentUDIField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentUDIField, value) != true)) {
                    this.DocumentUDIField = value;
                    this.RaisePropertyChanged("DocumentUDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerNo {
            get {
                return this.CustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNoField, value) != true)) {
                    this.CustomerNoField = value;
                    this.RaisePropertyChanged("CustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountNo {
            get {
                return this.AccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNoField, value) != true)) {
                    this.AccountNoField = value;
                    this.RaisePropertyChanged("AccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BufferID {
            get {
                return this.BufferIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BufferIDField, value) != true)) {
                    this.BufferIDField = value;
                    this.RaisePropertyChanged("BufferID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DocumentReference {
            get {
                return this.DocumentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentReferenceField, value) != true)) {
                    this.DocumentReferenceField = value;
                    this.RaisePropertyChanged("DocumentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ActionStatus {
            get {
                return this.ActionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionStatusField, value) != true)) {
                    this.ActionStatusField = value;
                    this.RaisePropertyChanged("ActionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string WorkLocation {
            get {
                return this.WorkLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkLocationField, value) != true)) {
                    this.WorkLocationField = value;
                    this.RaisePropertyChanged("WorkLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CaseReference {
            get {
                return this.CaseReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseReferenceField, value) != true)) {
                    this.CaseReferenceField = value;
                    this.RaisePropertyChanged("CaseReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ProcessStatus {
            get {
                return this.ProcessStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessStatusField, value) != true)) {
                    this.ProcessStatusField = value;
                    this.RaisePropertyChanged("ProcessStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CompletionDate {
            get {
                return this.CompletionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CompletionDateField, value) != true)) {
                    this.CompletionDateField = value;
                    this.RaisePropertyChanged("CompletionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DocumentDate {
            get {
                return this.DocumentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDateField, value) != true)) {
                    this.DocumentDateField = value;
                    this.RaisePropertyChanged("DocumentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DocumentTime {
            get {
                return this.DocumentTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTimeField, value) != true)) {
                    this.DocumentTimeField = value;
                    this.RaisePropertyChanged("DocumentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DSXUpdateResponse", Namespace="http://Bank.Service.DSXUpdate/")]
    [System.SerializableAttribute()]
    public partial class DSXUpdateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentUDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CaseReference {
            get {
                return this.CaseReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseReferenceField, value) != true)) {
                    this.CaseReferenceField = value;
                    this.RaisePropertyChanged("CaseReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentUDI {
            get {
                return this.DocumentUDIField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentUDIField, value) != true)) {
                    this.DocumentUDIField = value;
                    this.RaisePropertyChanged("DocumentUDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DSXUpdateRequests", Namespace="http://Bank.Service.DSXUpdate/")]
    [System.SerializableAttribute()]
    public partial class DSXUpdateRequests : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApexServices.DSXUpdates.DSXUpdateRequest[] DSXUpdRequestsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ApexServices.DSXUpdates.DSXUpdateRequest[] DSXUpdRequests {
            get {
                return this.DSXUpdRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.DSXUpdRequestsField, value) != true)) {
                    this.DSXUpdRequestsField = value;
                    this.RaisePropertyChanged("DSXUpdRequests");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DSXUpdateResponses", Namespace="http://Bank.Service.DSXUpdate/")]
    [System.SerializableAttribute()]
    public partial class DSXUpdateResponses : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApexServices.DSXUpdates.DSXUpdateResponse[] DSXUpdResponsesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ApexServices.DSXUpdates.DSXUpdateResponse[] DSXUpdResponses {
            get {
                return this.DSXUpdResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.DSXUpdResponsesField, value) != true)) {
                    this.DSXUpdResponsesField = value;
                    this.RaisePropertyChanged("DSXUpdResponses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Bank.Service.DSXUpdate/", ConfigurationName="DSXUpdates.DSXUpdateServiceSoap")]
    public interface DSXUpdateServiceSoap {
        
        // CODEGEN: Generating message contract since element name updateRequest from namespace http://Bank.Service.DSXUpdate/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Service.DSXUpdate/UpdateDSX", ReplyAction="*")]
        ApexServices.DSXUpdates.UpdateDSXResponse UpdateDSX(ApexServices.DSXUpdates.UpdateDSXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Service.DSXUpdate/UpdateDSX", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.DSXUpdates.UpdateDSXResponse> UpdateDSXAsync(ApexServices.DSXUpdates.UpdateDSXRequest request);
        
        // CODEGEN: Generating message contract since element name updateRequests from namespace http://Bank.Service.DSXUpdate/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Service.DSXUpdate/UpdatesDSX", ReplyAction="*")]
        ApexServices.DSXUpdates.UpdatesDSXResponse UpdatesDSX(ApexServices.DSXUpdates.UpdatesDSXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Service.DSXUpdate/UpdatesDSX", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.DSXUpdates.UpdatesDSXResponse> UpdatesDSXAsync(ApexServices.DSXUpdates.UpdatesDSXRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDSXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDSX", Namespace="http://Bank.Service.DSXUpdate/", Order=0)]
        public ApexServices.DSXUpdates.UpdateDSXRequestBody Body;
        
        public UpdateDSXRequest() {
        }
        
        public UpdateDSXRequest(ApexServices.DSXUpdates.UpdateDSXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Service.DSXUpdate/")]
    public partial class UpdateDSXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.DSXUpdates.DSXUpdateRequest updateRequest;
        
        public UpdateDSXRequestBody() {
        }
        
        public UpdateDSXRequestBody(ApexServices.DSXUpdates.DSXUpdateRequest updateRequest) {
            this.updateRequest = updateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDSXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDSXResponse", Namespace="http://Bank.Service.DSXUpdate/", Order=0)]
        public ApexServices.DSXUpdates.UpdateDSXResponseBody Body;
        
        public UpdateDSXResponse() {
        }
        
        public UpdateDSXResponse(ApexServices.DSXUpdates.UpdateDSXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Service.DSXUpdate/")]
    public partial class UpdateDSXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.DSXUpdates.DSXUpdateResponse UpdateDSXResult;
        
        public UpdateDSXResponseBody() {
        }
        
        public UpdateDSXResponseBody(ApexServices.DSXUpdates.DSXUpdateResponse UpdateDSXResult) {
            this.UpdateDSXResult = UpdateDSXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatesDSXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatesDSX", Namespace="http://Bank.Service.DSXUpdate/", Order=0)]
        public ApexServices.DSXUpdates.UpdatesDSXRequestBody Body;
        
        public UpdatesDSXRequest() {
        }
        
        public UpdatesDSXRequest(ApexServices.DSXUpdates.UpdatesDSXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Service.DSXUpdate/")]
    public partial class UpdatesDSXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.DSXUpdates.DSXUpdateRequests updateRequests;
        
        public UpdatesDSXRequestBody() {
        }
        
        public UpdatesDSXRequestBody(ApexServices.DSXUpdates.DSXUpdateRequests updateRequests) {
            this.updateRequests = updateRequests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatesDSXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatesDSXResponse", Namespace="http://Bank.Service.DSXUpdate/", Order=0)]
        public ApexServices.DSXUpdates.UpdatesDSXResponseBody Body;
        
        public UpdatesDSXResponse() {
        }
        
        public UpdatesDSXResponse(ApexServices.DSXUpdates.UpdatesDSXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Service.DSXUpdate/")]
    public partial class UpdatesDSXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.DSXUpdates.DSXUpdateResponses UpdatesDSXResult;
        
        public UpdatesDSXResponseBody() {
        }
        
        public UpdatesDSXResponseBody(ApexServices.DSXUpdates.DSXUpdateResponses UpdatesDSXResult) {
            this.UpdatesDSXResult = UpdatesDSXResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DSXUpdateServiceSoapChannel : ApexServices.DSXUpdates.DSXUpdateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DSXUpdateServiceSoapClient : System.ServiceModel.ClientBase<ApexServices.DSXUpdates.DSXUpdateServiceSoap>, ApexServices.DSXUpdates.DSXUpdateServiceSoap {
        
        public DSXUpdateServiceSoapClient() {
        }
        
        public DSXUpdateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DSXUpdateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSXUpdateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSXUpdateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.DSXUpdates.UpdateDSXResponse ApexServices.DSXUpdates.DSXUpdateServiceSoap.UpdateDSX(ApexServices.DSXUpdates.UpdateDSXRequest request) {
            return base.Channel.UpdateDSX(request);
        }
        
        public ApexServices.DSXUpdates.DSXUpdateResponse UpdateDSX(ApexServices.DSXUpdates.DSXUpdateRequest updateRequest) {
            ApexServices.DSXUpdates.UpdateDSXRequest inValue = new ApexServices.DSXUpdates.UpdateDSXRequest();
            inValue.Body = new ApexServices.DSXUpdates.UpdateDSXRequestBody();
            inValue.Body.updateRequest = updateRequest;
            ApexServices.DSXUpdates.UpdateDSXResponse retVal = ((ApexServices.DSXUpdates.DSXUpdateServiceSoap)(this)).UpdateDSX(inValue);
            return retVal.Body.UpdateDSXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.DSXUpdates.UpdateDSXResponse> ApexServices.DSXUpdates.DSXUpdateServiceSoap.UpdateDSXAsync(ApexServices.DSXUpdates.UpdateDSXRequest request) {
            return base.Channel.UpdateDSXAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.DSXUpdates.UpdateDSXResponse> UpdateDSXAsync(ApexServices.DSXUpdates.DSXUpdateRequest updateRequest) {
            ApexServices.DSXUpdates.UpdateDSXRequest inValue = new ApexServices.DSXUpdates.UpdateDSXRequest();
            inValue.Body = new ApexServices.DSXUpdates.UpdateDSXRequestBody();
            inValue.Body.updateRequest = updateRequest;
            return ((ApexServices.DSXUpdates.DSXUpdateServiceSoap)(this)).UpdateDSXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.DSXUpdates.UpdatesDSXResponse ApexServices.DSXUpdates.DSXUpdateServiceSoap.UpdatesDSX(ApexServices.DSXUpdates.UpdatesDSXRequest request) {
            return base.Channel.UpdatesDSX(request);
        }
        
        public ApexServices.DSXUpdates.DSXUpdateResponses UpdatesDSX(ApexServices.DSXUpdates.DSXUpdateRequests updateRequests) {
            ApexServices.DSXUpdates.UpdatesDSXRequest inValue = new ApexServices.DSXUpdates.UpdatesDSXRequest();
            inValue.Body = new ApexServices.DSXUpdates.UpdatesDSXRequestBody();
            inValue.Body.updateRequests = updateRequests;
            ApexServices.DSXUpdates.UpdatesDSXResponse retVal = ((ApexServices.DSXUpdates.DSXUpdateServiceSoap)(this)).UpdatesDSX(inValue);
            return retVal.Body.UpdatesDSXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.DSXUpdates.UpdatesDSXResponse> ApexServices.DSXUpdates.DSXUpdateServiceSoap.UpdatesDSXAsync(ApexServices.DSXUpdates.UpdatesDSXRequest request) {
            return base.Channel.UpdatesDSXAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.DSXUpdates.UpdatesDSXResponse> UpdatesDSXAsync(ApexServices.DSXUpdates.DSXUpdateRequests updateRequests) {
            ApexServices.DSXUpdates.UpdatesDSXRequest inValue = new ApexServices.DSXUpdates.UpdatesDSXRequest();
            inValue.Body = new ApexServices.DSXUpdates.UpdatesDSXRequestBody();
            inValue.Body.updateRequests = updateRequests;
            return ((ApexServices.DSXUpdates.DSXUpdateServiceSoap)(this)).UpdatesDSXAsync(inValue);
        }
    }
}
