//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.GetNoticeWithdrawalList {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetNoticeWithdrawals", Namespace="http://IBB.Services.EngageServices")]
    [System.SerializableAttribute()]
    public partial class GetNoticeWithdrawals : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkstationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WorkstationID {
            get {
                return this.WorkstationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkstationIDField, value) != true)) {
                    this.WorkstationIDField = value;
                    this.RaisePropertyChanged("WorkstationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetNoticeWithdrawalsResponse", Namespace="http://IBB.Services.EngageServices")]
    [System.SerializableAttribute()]
    public partial class GetNoticeWithdrawalsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApexServices.GetNoticeWithdrawalList.ArrayOfGetNoticeWithdrawalsResponseNoticeWithdrawalDetail NoticeWithdrawalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseDescription {
            get {
                return this.ResponseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDescriptionField, value) != true)) {
                    this.ResponseDescriptionField = value;
                    this.RaisePropertyChanged("ResponseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ApexServices.GetNoticeWithdrawalList.ArrayOfGetNoticeWithdrawalsResponseNoticeWithdrawalDetail NoticeWithdrawals {
            get {
                return this.NoticeWithdrawalsField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeWithdrawalsField, value) != true)) {
                    this.NoticeWithdrawalsField = value;
                    this.RaisePropertyChanged("NoticeWithdrawals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGetNoticeWithdrawalsResponseNoticeWithdrawalDetail", Namespace="http://IBB.Services.EngageServices", ItemName="NoticeWithdrawalDetail")]
    [System.SerializableAttribute()]
    public class ArrayOfGetNoticeWithdrawalsResponseNoticeWithdrawalDetail : System.Collections.Generic.List<ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoticeWithdrawalDetail", Namespace="http://IBB.Services.EngageServices")]
    [System.SerializableAttribute()]
    public partial class NoticeWithdrawalDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeGivenDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeMaturityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeBeneficiaryAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeBeneficiarySortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeBeneficiaryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeTransferMethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NoticeReference {
            get {
                return this.NoticeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeReferenceField, value) != true)) {
                    this.NoticeReferenceField = value;
                    this.RaisePropertyChanged("NoticeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NoticeGivenDate {
            get {
                return this.NoticeGivenDateField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeGivenDateField, value) != true)) {
                    this.NoticeGivenDateField = value;
                    this.RaisePropertyChanged("NoticeGivenDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NoticeMaturityDate {
            get {
                return this.NoticeMaturityDateField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeMaturityDateField, value) != true)) {
                    this.NoticeMaturityDateField = value;
                    this.RaisePropertyChanged("NoticeMaturityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NoticeAmount {
            get {
                return this.NoticeAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeAmountField, value) != true)) {
                    this.NoticeAmountField = value;
                    this.RaisePropertyChanged("NoticeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NoticeBeneficiaryAccountNumber {
            get {
                return this.NoticeBeneficiaryAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeBeneficiaryAccountNumberField, value) != true)) {
                    this.NoticeBeneficiaryAccountNumberField = value;
                    this.RaisePropertyChanged("NoticeBeneficiaryAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NoticeBeneficiarySortCode {
            get {
                return this.NoticeBeneficiarySortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeBeneficiarySortCodeField, value) != true)) {
                    this.NoticeBeneficiarySortCodeField = value;
                    this.RaisePropertyChanged("NoticeBeneficiarySortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NoticeBeneficiaryName {
            get {
                return this.NoticeBeneficiaryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeBeneficiaryNameField, value) != true)) {
                    this.NoticeBeneficiaryNameField = value;
                    this.RaisePropertyChanged("NoticeBeneficiaryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NoticeCurrency {
            get {
                return this.NoticeCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeCurrencyField, value) != true)) {
                    this.NoticeCurrencyField = value;
                    this.RaisePropertyChanged("NoticeCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NoticeStatus {
            get {
                return this.NoticeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeStatusField, value) != true)) {
                    this.NoticeStatusField = value;
                    this.RaisePropertyChanged("NoticeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NoticeTransferMethod {
            get {
                return this.NoticeTransferMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeTransferMethodField, value) != true)) {
                    this.NoticeTransferMethodField = value;
                    this.RaisePropertyChanged("NoticeTransferMethod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IBB.Services.CashierServices", ConfigurationName="GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_Re" +
        "ceiveGetNoticeWithdrawalsPortSoap")]
    public interface IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap {
        
        // CODEGEN: Generating message contract since element name GetNoticeWithdrawals from namespace http://IBB.Services.EngageServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://IBB.Services.CashierServices/IBB_Services_EngageServices_orcGetNoticeWithd" +
            "rawalList_ReceiveGetNoticeWithdrawalsPort/NoticeWithdrawalList", ReplyAction="*")]
        ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponse NoticeWithdrawalList(ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IBB.Services.CashierServices/IBB_Services_EngageServices_orcGetNoticeWithd" +
            "rawalList_ReceiveGetNoticeWithdrawalsPort/NoticeWithdrawalList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponse> NoticeWithdrawalListAsync(ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NoticeWithdrawalListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NoticeWithdrawalList", Namespace="http://IBB.Services.CashierServices", Order=0)]
        public ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequestBody Body;
        
        public NoticeWithdrawalListRequest() {
        }
        
        public NoticeWithdrawalListRequest(ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IBB.Services.EngageServices")]
    public partial class NoticeWithdrawalListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawals GetNoticeWithdrawals;
        
        public NoticeWithdrawalListRequestBody() {
        }
        
        public NoticeWithdrawalListRequestBody(ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawals GetNoticeWithdrawals) {
            this.GetNoticeWithdrawals = GetNoticeWithdrawals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NoticeWithdrawalListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NoticeWithdrawalListResponse", Namespace="http://IBB.Services.CashierServices", Order=0)]
        public ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponseBody Body;
        
        public NoticeWithdrawalListResponse() {
        }
        
        public NoticeWithdrawalListResponse(ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IBB.Services.EngageServices")]
    public partial class NoticeWithdrawalListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawalsResponse GetNoticeWithdrawalsResponse;
        
        public NoticeWithdrawalListResponseBody() {
        }
        
        public NoticeWithdrawalListResponseBody(ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawalsResponse GetNoticeWithdrawalsResponse) {
            this.GetNoticeWithdrawalsResponse = GetNoticeWithdrawalsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapChannel : ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapClient : System.ServiceModel.ClientBase<ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap>, ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap {
        
        public BB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapClient() {
        }
        
        public BB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponse ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap.NoticeWithdrawalList(ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest request) {
            return base.Channel.NoticeWithdrawalList(request);
        }
        
        public ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawalsResponse NoticeWithdrawalList(ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawals GetNoticeWithdrawals) {
            ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest inValue = new ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest();
            inValue.Body = new ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequestBody();
            inValue.Body.GetNoticeWithdrawals = GetNoticeWithdrawals;
            ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponse retVal = ((ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap)(this)).NoticeWithdrawalList(inValue);
            return retVal.Body.GetNoticeWithdrawalsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponse> ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap.NoticeWithdrawalListAsync(ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest request) {
            return base.Channel.NoticeWithdrawalListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListResponse> NoticeWithdrawalListAsync(ApexServices.GetNoticeWithdrawalList.GetNoticeWithdrawals GetNoticeWithdrawals) {
            ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest inValue = new ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequest();
            inValue.Body = new ApexServices.GetNoticeWithdrawalList.NoticeWithdrawalListRequestBody();
            inValue.Body.GetNoticeWithdrawals = GetNoticeWithdrawals;
            return ((ApexServices.GetNoticeWithdrawalList.IBB_Services_EngageServices_orcGetNoticeWithdrawalList_ReceiveGetNoticeWithdrawalsPortSoap)(this)).NoticeWithdrawalListAsync(inValue);
        }
    }
}
