//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.AccountTransfer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountTransferEngage", Namespace="http://IBB.Services.CashierServices")]
    [System.SerializableAttribute()]
    public partial class AccountTransferEngage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkstationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBSUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferFromAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferToAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferToSortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrativeLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrativeLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrativeLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrativeLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverrideUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeWithdrawalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeGivenDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeMaturityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CloseNoticeAccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WorkstationID {
            get {
                return this.WorkstationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkstationIDField, value) != true)) {
                    this.WorkstationIDField = value;
                    this.RaisePropertyChanged("WorkstationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EBSUserID {
            get {
                return this.EBSUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EBSUserIDField, value) != true)) {
                    this.EBSUserIDField = value;
                    this.RaisePropertyChanged("EBSUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TransferType {
            get {
                return this.TransferTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferTypeField, value) != true)) {
                    this.TransferTypeField = value;
                    this.RaisePropertyChanged("TransferType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TransferFromAccountNo {
            get {
                return this.TransferFromAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferFromAccountNoField, value) != true)) {
                    this.TransferFromAccountNoField = value;
                    this.RaisePropertyChanged("TransferFromAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TransferToAccountNo {
            get {
                return this.TransferToAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferToAccountNoField, value) != true)) {
                    this.TransferToAccountNoField = value;
                    this.RaisePropertyChanged("TransferToAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TransferToSortCode {
            get {
                return this.TransferToSortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferToSortCodeField, value) != true)) {
                    this.TransferToSortCodeField = value;
                    this.RaisePropertyChanged("TransferToSortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransferReference {
            get {
                return this.TransferReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferReferenceField, value) != true)) {
                    this.TransferReferenceField = value;
                    this.RaisePropertyChanged("TransferReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string BeneficiaryReference {
            get {
                return this.BeneficiaryReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryReferenceField, value) != true)) {
                    this.BeneficiaryReferenceField = value;
                    this.RaisePropertyChanged("BeneficiaryReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string BeneficiaryName {
            get {
                return this.BeneficiaryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryNameField, value) != true)) {
                    this.BeneficiaryNameField = value;
                    this.RaisePropertyChanged("BeneficiaryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TransferAmount {
            get {
                return this.TransferAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferAmountField, value) != true)) {
                    this.TransferAmountField = value;
                    this.RaisePropertyChanged("TransferAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeRateField, value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string TransferDueDate {
            get {
                return this.TransferDueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferDueDateField, value) != true)) {
                    this.TransferDueDateField = value;
                    this.RaisePropertyChanged("TransferDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string NarrativeLine1 {
            get {
                return this.NarrativeLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.NarrativeLine1Field, value) != true)) {
                    this.NarrativeLine1Field = value;
                    this.RaisePropertyChanged("NarrativeLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string NarrativeLine2 {
            get {
                return this.NarrativeLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NarrativeLine2Field, value) != true)) {
                    this.NarrativeLine2Field = value;
                    this.RaisePropertyChanged("NarrativeLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string NarrativeLine3 {
            get {
                return this.NarrativeLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.NarrativeLine3Field, value) != true)) {
                    this.NarrativeLine3Field = value;
                    this.RaisePropertyChanged("NarrativeLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string NarrativeLine4 {
            get {
                return this.NarrativeLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.NarrativeLine4Field, value) != true)) {
                    this.NarrativeLine4Field = value;
                    this.RaisePropertyChanged("NarrativeLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string TransferCurrency {
            get {
                return this.TransferCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferCurrencyField, value) != true)) {
                    this.TransferCurrencyField = value;
                    this.RaisePropertyChanged("TransferCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string DebitSystemParameter {
            get {
                return this.DebitSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitSystemParameterField, value) != true)) {
                    this.DebitSystemParameterField = value;
                    this.RaisePropertyChanged("DebitSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string CreditSystemParameter {
            get {
                return this.CreditSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditSystemParameterField, value) != true)) {
                    this.CreditSystemParameterField = value;
                    this.RaisePropertyChanged("CreditSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string OverrideUser {
            get {
                return this.OverrideUserField;
            }
            set {
                if ((object.ReferenceEquals(this.OverrideUserField, value) != true)) {
                    this.OverrideUserField = value;
                    this.RaisePropertyChanged("OverrideUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ChargeCode {
            get {
                return this.ChargeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeCodeField, value) != true)) {
                    this.ChargeCodeField = value;
                    this.RaisePropertyChanged("ChargeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ChargeAmount {
            get {
                return this.ChargeAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeAmountField, value) != true)) {
                    this.ChargeAmountField = value;
                    this.RaisePropertyChanged("ChargeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string DebitAccountNumber {
            get {
                return this.DebitAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitAccountNumberField, value) != true)) {
                    this.DebitAccountNumberField = value;
                    this.RaisePropertyChanged("DebitAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string CreditAccountNumber {
            get {
                return this.CreditAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditAccountNumberField, value) != true)) {
                    this.CreditAccountNumberField = value;
                    this.RaisePropertyChanged("CreditAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string Spare1 {
            get {
                return this.Spare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare1Field, value) != true)) {
                    this.Spare1Field = value;
                    this.RaisePropertyChanged("Spare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Spare2 {
            get {
                return this.Spare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare2Field, value) != true)) {
                    this.Spare2Field = value;
                    this.RaisePropertyChanged("Spare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string Spare3 {
            get {
                return this.Spare3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare3Field, value) != true)) {
                    this.Spare3Field = value;
                    this.RaisePropertyChanged("Spare3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string Spare4 {
            get {
                return this.Spare4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare4Field, value) != true)) {
                    this.Spare4Field = value;
                    this.RaisePropertyChanged("Spare4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string Spare5 {
            get {
                return this.Spare5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare5Field, value) != true)) {
                    this.Spare5Field = value;
                    this.RaisePropertyChanged("Spare5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string NoticeWithdrawalType {
            get {
                return this.NoticeWithdrawalTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeWithdrawalTypeField, value) != true)) {
                    this.NoticeWithdrawalTypeField = value;
                    this.RaisePropertyChanged("NoticeWithdrawalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string NoticeGivenDate {
            get {
                return this.NoticeGivenDateField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeGivenDateField, value) != true)) {
                    this.NoticeGivenDateField = value;
                    this.RaisePropertyChanged("NoticeGivenDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string NoticeMaturityDate {
            get {
                return this.NoticeMaturityDateField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeMaturityDateField, value) != true)) {
                    this.NoticeMaturityDateField = value;
                    this.RaisePropertyChanged("NoticeMaturityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string CloseNoticeAccount {
            get {
                return this.CloseNoticeAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CloseNoticeAccountField, value) != true)) {
                    this.CloseNoticeAccountField = value;
                    this.RaisePropertyChanged("CloseNoticeAccount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountTransferEngageResponse", Namespace="http://IBB.Services.CashierServices")]
    [System.SerializableAttribute()]
    public partial class AccountTransferEngageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WithdrawalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgStatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransferReference {
            get {
                return this.TransferReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferReferenceField, value) != true)) {
                    this.TransferReferenceField = value;
                    this.RaisePropertyChanged("TransferReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TransferDueDate {
            get {
                return this.TransferDueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferDueDateField, value) != true)) {
                    this.TransferDueDateField = value;
                    this.RaisePropertyChanged("TransferDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WithdrawalAmount {
            get {
                return this.WithdrawalAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.WithdrawalAmountField, value) != true)) {
                    this.WithdrawalAmountField = value;
                    this.RaisePropertyChanged("WithdrawalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MsgStatus {
            get {
                return this.MsgStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgStatusField, value) != true)) {
                    this.MsgStatusField = value;
                    this.RaisePropertyChanged("MsgStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MsgStatusDescription {
            get {
                return this.MsgStatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgStatusDescriptionField, value) != true)) {
                    this.MsgStatusDescriptionField = value;
                    this.RaisePropertyChanged("MsgStatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ResponseReference {
            get {
                return this.ResponseReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseReferenceField, value) != true)) {
                    this.ResponseReferenceField = value;
                    this.RaisePropertyChanged("ResponseReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Dated {
            get {
                return this.DatedField;
            }
            set {
                if ((object.ReferenceEquals(this.DatedField, value) != true)) {
                    this.DatedField = value;
                    this.RaisePropertyChanged("Dated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IBB.Services.CashierServices", ConfigurationName="AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccou" +
        "ntTransferEngagePortSoap")]
    public interface IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap {
        
        // CODEGEN: Generating message contract since element name AccountTransferEngage from namespace http://IBB.Services.CashierServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://IBB.Services.CashierServices/IBB_Services_EngageServices_orcAccountTransfe" +
            "rEngage_ReceiveAccountTransferEngagePort/AccountTransferEngage", ReplyAction="*")]
        ApexServices.AccountTransfer.AccountTransferEngageResponse1 AccountTransferEngage(ApexServices.AccountTransfer.AccountTransferEngageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IBB.Services.CashierServices/IBB_Services_EngageServices_orcAccountTransfe" +
            "rEngage_ReceiveAccountTransferEngagePort/AccountTransferEngage", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.AccountTransfer.AccountTransferEngageResponse1> AccountTransferEngageAsync(ApexServices.AccountTransfer.AccountTransferEngageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountTransferEngageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountTransferEngage", Namespace="http://IBB.Services.CashierServices", Order=0)]
        public ApexServices.AccountTransfer.AccountTransferEngageRequestBody Body;
        
        public AccountTransferEngageRequest() {
        }
        
        public AccountTransferEngageRequest(ApexServices.AccountTransfer.AccountTransferEngageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IBB.Services.CashierServices")]
    public partial class AccountTransferEngageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.AccountTransfer.AccountTransferEngage AccountTransferEngage;
        
        public AccountTransferEngageRequestBody() {
        }
        
        public AccountTransferEngageRequestBody(ApexServices.AccountTransfer.AccountTransferEngage AccountTransferEngage) {
            this.AccountTransferEngage = AccountTransferEngage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountTransferEngageResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountTransferEngageResponse", Namespace="http://IBB.Services.CashierServices", Order=0)]
        public ApexServices.AccountTransfer.AccountTransferEngageResponse1Body Body;
        
        public AccountTransferEngageResponse1() {
        }
        
        public AccountTransferEngageResponse1(ApexServices.AccountTransfer.AccountTransferEngageResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IBB.Services.CashierServices")]
    public partial class AccountTransferEngageResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.AccountTransfer.AccountTransferEngageResponse AccountTransferEngageResponse;
        
        public AccountTransferEngageResponse1Body() {
        }
        
        public AccountTransferEngageResponse1Body(ApexServices.AccountTransfer.AccountTransferEngageResponse AccountTransferEngageResponse) {
            this.AccountTransferEngageResponse = AccountTransferEngageResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapChannel : ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapClient : System.ServiceModel.ClientBase<ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap>, ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap {
        
        public BB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapClient() {
        }
        
        public BB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.AccountTransfer.AccountTransferEngageResponse1 ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap.AccountTransferEngage(ApexServices.AccountTransfer.AccountTransferEngageRequest request) {
            return base.Channel.AccountTransferEngage(request);
        }
        
        public ApexServices.AccountTransfer.AccountTransferEngageResponse AccountTransferEngage(ApexServices.AccountTransfer.AccountTransferEngage AccountTransferEngage1) {
            ApexServices.AccountTransfer.AccountTransferEngageRequest inValue = new ApexServices.AccountTransfer.AccountTransferEngageRequest();
            inValue.Body = new ApexServices.AccountTransfer.AccountTransferEngageRequestBody();
            inValue.Body.AccountTransferEngage = AccountTransferEngage1;
            ApexServices.AccountTransfer.AccountTransferEngageResponse1 retVal = ((ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap)(this)).AccountTransferEngage(inValue);
            return retVal.Body.AccountTransferEngageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.AccountTransfer.AccountTransferEngageResponse1> ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap.AccountTransferEngageAsync(ApexServices.AccountTransfer.AccountTransferEngageRequest request) {
            return base.Channel.AccountTransferEngageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.AccountTransfer.AccountTransferEngageResponse1> AccountTransferEngageAsync(ApexServices.AccountTransfer.AccountTransferEngage AccountTransferEngage) {
            ApexServices.AccountTransfer.AccountTransferEngageRequest inValue = new ApexServices.AccountTransfer.AccountTransferEngageRequest();
            inValue.Body = new ApexServices.AccountTransfer.AccountTransferEngageRequestBody();
            inValue.Body.AccountTransferEngage = AccountTransferEngage;
            return ((ApexServices.AccountTransfer.IBB_Services_EngageServices_orcAccountTransferEngage_ReceiveAccountTransferEngagePortSoap)(this)).AccountTransferEngageAsync(inValue);
        }
    }
}
