//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.FXCashDeposit {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FXCashDepositEngage", Namespace="http://Bank.Biztalk.FXServices")]
    [System.SerializableAttribute()]
    public partial class FXCashDepositEngage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepositCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepositAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBSUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverrideUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepositCurrency {
            get {
                return this.DepositCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositCurrencyField, value) != true)) {
                    this.DepositCurrencyField = value;
                    this.RaisePropertyChanged("DepositCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExchangeCurrency {
            get {
                return this.ExchangeCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeCurrencyField, value) != true)) {
                    this.ExchangeCurrencyField = value;
                    this.RaisePropertyChanged("ExchangeCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DepositAmount {
            get {
                return this.DepositAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositAmountField, value) != true)) {
                    this.DepositAmountField = value;
                    this.RaisePropertyChanged("DepositAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExchangeAmount {
            get {
                return this.ExchangeAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeAmountField, value) != true)) {
                    this.ExchangeAmountField = value;
                    this.RaisePropertyChanged("ExchangeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeRateField, value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ValueDate {
            get {
                return this.ValueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueDateField, value) != true)) {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TransactionNarrativeLine1 {
            get {
                return this.TransactionNarrativeLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine1Field, value) != true)) {
                    this.TransactionNarrativeLine1Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TransactionNarrativeLine2 {
            get {
                return this.TransactionNarrativeLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine2Field, value) != true)) {
                    this.TransactionNarrativeLine2Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TransactionNarrativeLine3 {
            get {
                return this.TransactionNarrativeLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine3Field, value) != true)) {
                    this.TransactionNarrativeLine3Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TransactionNarrativeLine4 {
            get {
                return this.TransactionNarrativeLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine4Field, value) != true)) {
                    this.TransactionNarrativeLine4Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DebitSystemParameter {
            get {
                return this.DebitSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitSystemParameterField, value) != true)) {
                    this.DebitSystemParameterField = value;
                    this.RaisePropertyChanged("DebitSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CreditSystemParameter {
            get {
                return this.CreditSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditSystemParameterField, value) != true)) {
                    this.CreditSystemParameterField = value;
                    this.RaisePropertyChanged("CreditSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string EBSUserID {
            get {
                return this.EBSUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EBSUserIDField, value) != true)) {
                    this.EBSUserIDField = value;
                    this.RaisePropertyChanged("EBSUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string OverrideUser {
            get {
                return this.OverrideUserField;
            }
            set {
                if ((object.ReferenceEquals(this.OverrideUserField, value) != true)) {
                    this.OverrideUserField = value;
                    this.RaisePropertyChanged("OverrideUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string DebitAccountNumber {
            get {
                return this.DebitAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitAccountNumberField, value) != true)) {
                    this.DebitAccountNumberField = value;
                    this.RaisePropertyChanged("DebitAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CreditAccountNumber {
            get {
                return this.CreditAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditAccountNumberField, value) != true)) {
                    this.CreditAccountNumberField = value;
                    this.RaisePropertyChanged("CreditAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Spare1 {
            get {
                return this.Spare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare1Field, value) != true)) {
                    this.Spare1Field = value;
                    this.RaisePropertyChanged("Spare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Spare2 {
            get {
                return this.Spare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare2Field, value) != true)) {
                    this.Spare2Field = value;
                    this.RaisePropertyChanged("Spare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Spare3 {
            get {
                return this.Spare3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare3Field, value) != true)) {
                    this.Spare3Field = value;
                    this.RaisePropertyChanged("Spare3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Spare4 {
            get {
                return this.Spare4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare4Field, value) != true)) {
                    this.Spare4Field = value;
                    this.RaisePropertyChanged("Spare4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Spare5 {
            get {
                return this.Spare5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare5Field, value) != true)) {
                    this.Spare5Field = value;
                    this.RaisePropertyChanged("Spare5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FXCashDepositResponse", Namespace="http://Bank.Biztalk.FXServices")]
    [System.SerializableAttribute()]
    public partial class FXCashDepositResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseText {
            get {
                return this.ResponseTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseTextField, value) != true)) {
                    this.ResponseTextField = value;
                    this.RaisePropertyChanged("ResponseText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Bank.Biztalk.FXServices", ConfigurationName="FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDeposi" +
        "tPortSoap")]
    public interface Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap {
        
        // CODEGEN: Generating message contract since element name FXCashDepositEngage from namespace http://Bank.Biztalk.FXServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FXServices/Bank_Biztalk_FXServices_orcProcessFXCashDeposit_Re" +
            "ceiveFXCashDepositPort/FXCashDeposit", ReplyAction="*")]
        ApexServices.FXCashDeposit.FXCashDepositResponse1 FXCashDeposit(ApexServices.FXCashDeposit.FXCashDepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FXServices/Bank_Biztalk_FXServices_orcProcessFXCashDeposit_Re" +
            "ceiveFXCashDepositPort/FXCashDeposit", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.FXCashDeposit.FXCashDepositResponse1> FXCashDepositAsync(ApexServices.FXCashDeposit.FXCashDepositRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXCashDepositRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXCashDeposit", Namespace="http://Bank.Biztalk.FXServices", Order=0)]
        public ApexServices.FXCashDeposit.FXCashDepositRequestBody Body;
        
        public FXCashDepositRequest() {
        }
        
        public FXCashDepositRequest(ApexServices.FXCashDeposit.FXCashDepositRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FXServices")]
    public partial class FXCashDepositRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FXCashDeposit.FXCashDepositEngage FXCashDepositEngage;
        
        public FXCashDepositRequestBody() {
        }
        
        public FXCashDepositRequestBody(ApexServices.FXCashDeposit.FXCashDepositEngage FXCashDepositEngage) {
            this.FXCashDepositEngage = FXCashDepositEngage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXCashDepositResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXCashDepositResponse", Namespace="http://Bank.Biztalk.FXServices", Order=0)]
        public ApexServices.FXCashDeposit.FXCashDepositResponse1Body Body;
        
        public FXCashDepositResponse1() {
        }
        
        public FXCashDepositResponse1(ApexServices.FXCashDeposit.FXCashDepositResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FXServices")]
    public partial class FXCashDepositResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FXCashDeposit.FXCashDepositResponse FXCashDepositResponse;
        
        public FXCashDepositResponse1Body() {
        }
        
        public FXCashDepositResponse1Body(ApexServices.FXCashDeposit.FXCashDepositResponse FXCashDepositResponse) {
            this.FXCashDepositResponse = FXCashDepositResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapChannel : ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapClient : System.ServiceModel.ClientBase<ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap>, ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap {
        
        public Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapClient() {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.FXCashDeposit.FXCashDepositResponse1 ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap.FXCashDeposit(ApexServices.FXCashDeposit.FXCashDepositRequest request) {
            return base.Channel.FXCashDeposit(request);
        }
        
        public ApexServices.FXCashDeposit.FXCashDepositResponse FXCashDeposit(ApexServices.FXCashDeposit.FXCashDepositEngage FXCashDepositEngage) {
            ApexServices.FXCashDeposit.FXCashDepositRequest inValue = new ApexServices.FXCashDeposit.FXCashDepositRequest();
            inValue.Body = new ApexServices.FXCashDeposit.FXCashDepositRequestBody();
            inValue.Body.FXCashDepositEngage = FXCashDepositEngage;
            ApexServices.FXCashDeposit.FXCashDepositResponse1 retVal = ((ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap)(this)).FXCashDeposit(inValue);
            return retVal.Body.FXCashDepositResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.FXCashDeposit.FXCashDepositResponse1> ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap.FXCashDepositAsync(ApexServices.FXCashDeposit.FXCashDepositRequest request) {
            return base.Channel.FXCashDepositAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.FXCashDeposit.FXCashDepositResponse1> FXCashDepositAsync(ApexServices.FXCashDeposit.FXCashDepositEngage FXCashDepositEngage) {
            ApexServices.FXCashDeposit.FXCashDepositRequest inValue = new ApexServices.FXCashDeposit.FXCashDepositRequest();
            inValue.Body = new ApexServices.FXCashDeposit.FXCashDepositRequestBody();
            inValue.Body.FXCashDepositEngage = FXCashDepositEngage;
            return ((ApexServices.FXCashDeposit.Bank_Biztalk_FXServices_orcProcessFXCashDeposit_ReceiveFXCashDepositPortSoap)(this)).FXCashDepositAsync(inValue);
        }
    }
}
