//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.PayeeList {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPayeeList", Namespace="http://IBB.Services.EngageServices")]
    [System.SerializableAttribute()]
    public partial class GetPayeeList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkstationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WorkstationID {
            get {
                return this.WorkstationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkstationIDField, value) != true)) {
                    this.WorkstationIDField = value;
                    this.RaisePropertyChanged("WorkstationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomerNo {
            get {
                return this.CustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNoField, value) != true)) {
                    this.CustomerNoField = value;
                    this.RaisePropertyChanged("CustomerNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPayeeListResponse", Namespace="http://IBB.Services.EngageServices")]
    [System.SerializableAttribute()]
    public partial class GetPayeeListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApexServices.PayeeList.ArrayOfGetPayeeListResponsePayee PayeeListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResponseDescription {
            get {
                return this.ResponseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDescriptionField, value) != true)) {
                    this.ResponseDescriptionField = value;
                    this.RaisePropertyChanged("ResponseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ApexServices.PayeeList.ArrayOfGetPayeeListResponsePayee PayeeList {
            get {
                return this.PayeeListField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeListField, value) != true)) {
                    this.PayeeListField = value;
                    this.RaisePropertyChanged("PayeeList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGetPayeeListResponsePayee", Namespace="http://IBB.Services.EngageServices", ItemName="Payee")]
    [System.SerializableAttribute()]
    public class ArrayOfGetPayeeListResponsePayee : System.Collections.Generic.List<ApexServices.PayeeList.Payee> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payee", Namespace="http://IBB.Services.EngageServices")]
    [System.SerializableAttribute()]
    public partial class Payee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hostcustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayeeRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayerRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayBranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayAcctIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bPayPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bPaybankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bPayBranchAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bPayBranchAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bPayBranchCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsDomesticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsGlobalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NominatedForDebitAcctIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsNPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string hostcustomerId {
            get {
                return this.hostcustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.hostcustomerIdField, value) != true)) {
                    this.hostcustomerIdField = value;
                    this.RaisePropertyChanged("hostcustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PayeeId {
            get {
                return this.PayeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeIdField, value) != true)) {
                    this.PayeeIdField = value;
                    this.RaisePropertyChanged("PayeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PayeeName {
            get {
                return this.PayeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeNameField, value) != true)) {
                    this.PayeeNameField = value;
                    this.RaisePropertyChanged("PayeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PayeeRef {
            get {
                return this.PayeeRefField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeRefField, value) != true)) {
                    this.PayeeRefField = value;
                    this.RaisePropertyChanged("PayeeRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PayerRef {
            get {
                return this.PayerRefField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerRefField, value) != true)) {
                    this.PayerRefField = value;
                    this.RaisePropertyChanged("PayerRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PayBranchId {
            get {
                return this.PayBranchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayBranchIdField, value) != true)) {
                    this.PayBranchIdField = value;
                    this.RaisePropertyChanged("PayBranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PayAcctId {
            get {
                return this.PayAcctIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayAcctIdField, value) != true)) {
                    this.PayAcctIdField = value;
                    this.RaisePropertyChanged("PayAcctId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Branchname {
            get {
                return this.BranchnameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchnameField, value) != true)) {
                    this.BranchnameField = value;
                    this.RaisePropertyChanged("Branchname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string bAddress1 {
            get {
                return this.bAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.bAddress1Field, value) != true)) {
                    this.bAddress1Field = value;
                    this.RaisePropertyChanged("bAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string bAddress2 {
            get {
                return this.bAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.bAddress2Field, value) != true)) {
                    this.bAddress2Field = value;
                    this.RaisePropertyChanged("bAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string bCity {
            get {
                return this.bCityField;
            }
            set {
                if ((object.ReferenceEquals(this.bCityField, value) != true)) {
                    this.bCityField = value;
                    this.RaisePropertyChanged("bCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string bCounty {
            get {
                return this.bCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.bCountyField, value) != true)) {
                    this.bCountyField = value;
                    this.RaisePropertyChanged("bCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string bCountry {
            get {
                return this.bCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.bCountryField, value) != true)) {
                    this.bCountryField = value;
                    this.RaisePropertyChanged("bCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string bPostCode {
            get {
                return this.bPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.bPostCodeField, value) != true)) {
                    this.bPostCodeField = value;
                    this.RaisePropertyChanged("bPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string bPayPhone {
            get {
                return this.bPayPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.bPayPhoneField, value) != true)) {
                    this.bPayPhoneField = value;
                    this.RaisePropertyChanged("bPayPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string bPaybankName {
            get {
                return this.bPaybankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bPaybankNameField, value) != true)) {
                    this.bPaybankNameField = value;
                    this.RaisePropertyChanged("bPaybankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string bPayBranchAddress1 {
            get {
                return this.bPayBranchAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.bPayBranchAddress1Field, value) != true)) {
                    this.bPayBranchAddress1Field = value;
                    this.RaisePropertyChanged("bPayBranchAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string bPayBranchAddress2 {
            get {
                return this.bPayBranchAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.bPayBranchAddress2Field, value) != true)) {
                    this.bPayBranchAddress2Field = value;
                    this.RaisePropertyChanged("bPayBranchAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string bPayBranchCity {
            get {
                return this.bPayBranchCityField;
            }
            set {
                if ((object.ReferenceEquals(this.bPayBranchCityField, value) != true)) {
                    this.bPayBranchCityField = value;
                    this.RaisePropertyChanged("bPayBranchCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string IsDomestic {
            get {
                return this.IsDomesticField;
            }
            set {
                if ((object.ReferenceEquals(this.IsDomesticField, value) != true)) {
                    this.IsDomesticField = value;
                    this.RaisePropertyChanged("IsDomestic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string IsGlobal {
            get {
                return this.IsGlobalField;
            }
            set {
                if ((object.ReferenceEquals(this.IsGlobalField, value) != true)) {
                    this.IsGlobalField = value;
                    this.RaisePropertyChanged("IsGlobal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string NominatedForDebitAcctID {
            get {
                return this.NominatedForDebitAcctIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NominatedForDebitAcctIDField, value) != true)) {
                    this.NominatedForDebitAcctIDField = value;
                    this.RaisePropertyChanged("NominatedForDebitAcctID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string IsNP {
            get {
                return this.IsNPField;
            }
            set {
                if ((object.ReferenceEquals(this.IsNPField, value) != true)) {
                    this.IsNPField = value;
                    this.RaisePropertyChanged("IsNP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IBB.Services.EngageServices", ConfigurationName="PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoa" +
        "p")]
    public interface IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap {
        
        // CODEGEN: Generating message contract since element name GetPayeeList from namespace http://IBB.Services.EngageServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://IBB.Services.EngageServices/IBB_Services_EngageServices_orcPayeeList_Recei" +
            "vePayeeListRequestPort/PayeeList", ReplyAction="*")]
        ApexServices.PayeeList.PayeeListResponse PayeeList(ApexServices.PayeeList.PayeeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IBB.Services.EngageServices/IBB_Services_EngageServices_orcPayeeList_Recei" +
            "vePayeeListRequestPort/PayeeList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.PayeeList.PayeeListResponse> PayeeListAsync(ApexServices.PayeeList.PayeeListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayeeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayeeList", Namespace="http://IBB.Services.EngageServices", Order=0)]
        public ApexServices.PayeeList.PayeeListRequestBody Body;
        
        public PayeeListRequest() {
        }
        
        public PayeeListRequest(ApexServices.PayeeList.PayeeListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IBB.Services.EngageServices")]
    public partial class PayeeListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.PayeeList.GetPayeeList GetPayeeList;
        
        public PayeeListRequestBody() {
        }
        
        public PayeeListRequestBody(ApexServices.PayeeList.GetPayeeList GetPayeeList) {
            this.GetPayeeList = GetPayeeList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayeeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayeeListResponse", Namespace="http://IBB.Services.EngageServices", Order=0)]
        public ApexServices.PayeeList.PayeeListResponseBody Body;
        
        public PayeeListResponse() {
        }
        
        public PayeeListResponse(ApexServices.PayeeList.PayeeListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IBB.Services.EngageServices")]
    public partial class PayeeListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.PayeeList.GetPayeeListResponse GetPayeeListResponse;
        
        public PayeeListResponseBody() {
        }
        
        public PayeeListResponseBody(ApexServices.PayeeList.GetPayeeListResponse GetPayeeListResponse) {
            this.GetPayeeListResponse = GetPayeeListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapChannel : ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapClient : System.ServiceModel.ClientBase<ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap>, ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap {
        
        public BB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapClient() {
        }
        
        public BB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.PayeeList.PayeeListResponse ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap.PayeeList(ApexServices.PayeeList.PayeeListRequest request) {
            return base.Channel.PayeeList(request);
        }
        
        public ApexServices.PayeeList.GetPayeeListResponse PayeeList(ApexServices.PayeeList.GetPayeeList GetPayeeList) {
            ApexServices.PayeeList.PayeeListRequest inValue = new ApexServices.PayeeList.PayeeListRequest();
            inValue.Body = new ApexServices.PayeeList.PayeeListRequestBody();
            inValue.Body.GetPayeeList = GetPayeeList;
            ApexServices.PayeeList.PayeeListResponse retVal = ((ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap)(this)).PayeeList(inValue);
            return retVal.Body.GetPayeeListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.PayeeList.PayeeListResponse> ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap.PayeeListAsync(ApexServices.PayeeList.PayeeListRequest request) {
            return base.Channel.PayeeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.PayeeList.PayeeListResponse> PayeeListAsync(ApexServices.PayeeList.GetPayeeList GetPayeeList) {
            ApexServices.PayeeList.PayeeListRequest inValue = new ApexServices.PayeeList.PayeeListRequest();
            inValue.Body = new ApexServices.PayeeList.PayeeListRequestBody();
            inValue.Body.GetPayeeList = GetPayeeList;
            return ((ApexServices.PayeeList.IBB_Services_EngageServices_orcPayeeList_ReceivePayeeListRequestPortSoap)(this)).PayeeListAsync(inValue);
        }
    }
}
