//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.DirectDebit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.islamic-bank.com/IBBWebServices", ConfigurationName="DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap")]
    public interface IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB) does not match the default value (http://www.islamic-bank.com/IBBWebServices)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.islamic-bank.com/IBBWebServices/IBBWebServices_AccountDD_AccountDDOrch" +
            "_AccountDD_Port/AccountDDOrch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IBBAccountDDResult")]
        ApexServices.DirectDebit.AccountDDOrchResponse AccountDDOrch(ApexServices.DirectDebit.AccountDDOrchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.islamic-bank.com/IBBWebServices/IBBWebServices_AccountDD_AccountDDOrch" +
            "_AccountDD_Port/AccountDDOrch", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.DirectDebit.AccountDDOrchResponse> AccountDDOrchAsync(ApexServices.DirectDebit.AccountDDOrchRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB")]
    public partial class IBBAccountDD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNoField;
        
        private string sourceIDField;
        
        private string workstationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("AccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
                this.RaisePropertyChanged("SourceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string WorkstationID {
            get {
                return this.workstationIDField;
            }
            set {
                this.workstationIDField = value;
                this.RaisePropertyChanged("WorkstationID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB")]
    public partial class IBBAccountDDResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IBBAccountDDResultSecurityValidationRoot securityValidationRootField;
        
        private IBBAccountDDResultDDResult[] dDResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IBBAccountDDResultSecurityValidationRoot SecurityValidationRoot {
            get {
                return this.securityValidationRootField;
            }
            set {
                this.securityValidationRootField = value;
                this.RaisePropertyChanged("SecurityValidationRoot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DDResult", Order=1)]
        public IBBAccountDDResultDDResult[] DDResult {
            get {
                return this.dDResultField;
            }
            set {
                this.dDResultField = value;
                this.RaisePropertyChanged("DDResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB")]
    public partial class IBBAccountDDResultSecurityValidationRoot : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string securityValidationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SecurityValidation {
            get {
                return this.securityValidationField;
            }
            set {
                this.securityValidationField = value;
                this.RaisePropertyChanged("SecurityValidation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB")]
    public partial class IBBAccountDDResultDDResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dDInternalRefField;
        
        private string dDOrganisationNameField;
        
        private string dDOrganisationIDField;
        
        private string dDOrganisationRefField;
        
        private string dDStatusField;
        
        private string lastPaymentDateField;
        
        private string errorMessageField;
        
        private string warningMessageField;
        
        private string messageCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DDInternalRef {
            get {
                return this.dDInternalRefField;
            }
            set {
                this.dDInternalRefField = value;
                this.RaisePropertyChanged("DDInternalRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DDOrganisationName {
            get {
                return this.dDOrganisationNameField;
            }
            set {
                this.dDOrganisationNameField = value;
                this.RaisePropertyChanged("DDOrganisationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DDOrganisationID {
            get {
                return this.dDOrganisationIDField;
            }
            set {
                this.dDOrganisationIDField = value;
                this.RaisePropertyChanged("DDOrganisationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DDOrganisationRef {
            get {
                return this.dDOrganisationRefField;
            }
            set {
                this.dDOrganisationRefField = value;
                this.RaisePropertyChanged("DDOrganisationRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DDStatus {
            get {
                return this.dDStatusField;
            }
            set {
                this.dDStatusField = value;
                this.RaisePropertyChanged("DDStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastPaymentDate {
            get {
                return this.lastPaymentDateField;
            }
            set {
                this.lastPaymentDateField = value;
                this.RaisePropertyChanged("LastPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WarningMessage {
            get {
                return this.warningMessageField;
            }
            set {
                this.warningMessageField = value;
                this.RaisePropertyChanged("WarningMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountDDOrch", WrapperNamespace="http://www.islamic-bank.com/IBBWebServices", IsWrapped=true)]
    public partial class AccountDDOrchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB")]
        public ApexServices.DirectDebit.IBBAccountDD IBBAccountDD;
        
        public AccountDDOrchRequest() {
        }
        
        public AccountDDOrchRequest(ApexServices.DirectDebit.IBBAccountDD IBBAccountDD) {
            this.IBBAccountDD = IBBAccountDD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountDDOrchResponse", WrapperNamespace="http://www.islamic-bank.com/IBBWebServices", IsWrapped=true)]
    public partial class AccountDDOrchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.islamic-bank.com/IBBWebServices/AccountDD/FromIBB")]
        public ApexServices.DirectDebit.IBBAccountDDResult IBBAccountDDResult;
        
        public AccountDDOrchResponse() {
        }
        
        public AccountDDOrchResponse(ApexServices.DirectDebit.IBBAccountDDResult IBBAccountDDResult) {
            this.IBBAccountDDResult = IBBAccountDDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapChannel : ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapClient : System.ServiceModel.ClientBase<ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap>, ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap {
        
        public BBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapClient() {
        }
        
        public BBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.DirectDebit.AccountDDOrchResponse ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap.AccountDDOrch(ApexServices.DirectDebit.AccountDDOrchRequest request) {
            return base.Channel.AccountDDOrch(request);
        }
        
        public ApexServices.DirectDebit.IBBAccountDDResult AccountDDOrch(ApexServices.DirectDebit.IBBAccountDD IBBAccountDD) {
            ApexServices.DirectDebit.AccountDDOrchRequest inValue = new ApexServices.DirectDebit.AccountDDOrchRequest();
            inValue.IBBAccountDD = IBBAccountDD;
            ApexServices.DirectDebit.AccountDDOrchResponse retVal = ((ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap)(this)).AccountDDOrch(inValue);
            return retVal.IBBAccountDDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.DirectDebit.AccountDDOrchResponse> ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap.AccountDDOrchAsync(ApexServices.DirectDebit.AccountDDOrchRequest request) {
            return base.Channel.AccountDDOrchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.DirectDebit.AccountDDOrchResponse> AccountDDOrchAsync(ApexServices.DirectDebit.IBBAccountDD IBBAccountDD) {
            ApexServices.DirectDebit.AccountDDOrchRequest inValue = new ApexServices.DirectDebit.AccountDDOrchRequest();
            inValue.IBBAccountDD = IBBAccountDD;
            return ((ApexServices.DirectDebit.IBBWebServices_AccountDD_AccountDDOrch_AccountDD_PortSoap)(this)).AccountDDOrchAsync(inValue);
        }
    }
}
