//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.FXExchangeCash {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeCashEngage", Namespace="http://Bank.Biztalk.FXServices")]
    [System.SerializableAttribute()]
    public partial class ExchangeCashEngage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBSUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverrideUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundingBuyCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundingSellCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundingBuyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundingSellAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BuyCurrency {
            get {
                return this.BuyCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyCurrencyField, value) != true)) {
                    this.BuyCurrencyField = value;
                    this.RaisePropertyChanged("BuyCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SellCurrency {
            get {
                return this.SellCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.SellCurrencyField, value) != true)) {
                    this.SellCurrencyField = value;
                    this.RaisePropertyChanged("SellCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BuyAmount {
            get {
                return this.BuyAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyAmountField, value) != true)) {
                    this.BuyAmountField = value;
                    this.RaisePropertyChanged("BuyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SellAmount {
            get {
                return this.SellAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.SellAmountField, value) != true)) {
                    this.SellAmountField = value;
                    this.RaisePropertyChanged("SellAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeRateField, value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ValueDate {
            get {
                return this.ValueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueDateField, value) != true)) {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TransactionNarrativeLine1 {
            get {
                return this.TransactionNarrativeLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine1Field, value) != true)) {
                    this.TransactionNarrativeLine1Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TransactionNarrativeLine2 {
            get {
                return this.TransactionNarrativeLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine2Field, value) != true)) {
                    this.TransactionNarrativeLine2Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TransactionNarrativeLine3 {
            get {
                return this.TransactionNarrativeLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine3Field, value) != true)) {
                    this.TransactionNarrativeLine3Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TransactionNarrativeLine4 {
            get {
                return this.TransactionNarrativeLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine4Field, value) != true)) {
                    this.TransactionNarrativeLine4Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DebitSystemParameter {
            get {
                return this.DebitSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitSystemParameterField, value) != true)) {
                    this.DebitSystemParameterField = value;
                    this.RaisePropertyChanged("DebitSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CreditSystemParameter {
            get {
                return this.CreditSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditSystemParameterField, value) != true)) {
                    this.CreditSystemParameterField = value;
                    this.RaisePropertyChanged("CreditSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string EBSUserID {
            get {
                return this.EBSUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EBSUserIDField, value) != true)) {
                    this.EBSUserIDField = value;
                    this.RaisePropertyChanged("EBSUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string OverrideUser {
            get {
                return this.OverrideUserField;
            }
            set {
                if ((object.ReferenceEquals(this.OverrideUserField, value) != true)) {
                    this.OverrideUserField = value;
                    this.RaisePropertyChanged("OverrideUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string DebitAccountNumber {
            get {
                return this.DebitAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitAccountNumberField, value) != true)) {
                    this.DebitAccountNumberField = value;
                    this.RaisePropertyChanged("DebitAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CreditAccountNumber {
            get {
                return this.CreditAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditAccountNumberField, value) != true)) {
                    this.CreditAccountNumberField = value;
                    this.RaisePropertyChanged("CreditAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string RoundingBuyCurrency {
            get {
                return this.RoundingBuyCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundingBuyCurrencyField, value) != true)) {
                    this.RoundingBuyCurrencyField = value;
                    this.RaisePropertyChanged("RoundingBuyCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string RoundingSellCurrency {
            get {
                return this.RoundingSellCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundingSellCurrencyField, value) != true)) {
                    this.RoundingSellCurrencyField = value;
                    this.RaisePropertyChanged("RoundingSellCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string RoundingBuyAmount {
            get {
                return this.RoundingBuyAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundingBuyAmountField, value) != true)) {
                    this.RoundingBuyAmountField = value;
                    this.RaisePropertyChanged("RoundingBuyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string RoundingSellAmount {
            get {
                return this.RoundingSellAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundingSellAmountField, value) != true)) {
                    this.RoundingSellAmountField = value;
                    this.RaisePropertyChanged("RoundingSellAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Spare1 {
            get {
                return this.Spare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare1Field, value) != true)) {
                    this.Spare1Field = value;
                    this.RaisePropertyChanged("Spare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Spare2 {
            get {
                return this.Spare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare2Field, value) != true)) {
                    this.Spare2Field = value;
                    this.RaisePropertyChanged("Spare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Spare3 {
            get {
                return this.Spare3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare3Field, value) != true)) {
                    this.Spare3Field = value;
                    this.RaisePropertyChanged("Spare3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string Spare4 {
            get {
                return this.Spare4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare4Field, value) != true)) {
                    this.Spare4Field = value;
                    this.RaisePropertyChanged("Spare4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Spare5 {
            get {
                return this.Spare5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare5Field, value) != true)) {
                    this.Spare5Field = value;
                    this.RaisePropertyChanged("Spare5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FXExchangeCashResponse", Namespace="http://Bank.Biztalk.FXServices")]
    [System.SerializableAttribute()]
    public partial class FXExchangeCashResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundingTransferReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseText {
            get {
                return this.ResponseTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseTextField, value) != true)) {
                    this.ResponseTextField = value;
                    this.RaisePropertyChanged("ResponseText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RoundingTransferReference {
            get {
                return this.RoundingTransferReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundingTransferReferenceField, value) != true)) {
                    this.RoundingTransferReferenceField = value;
                    this.RaisePropertyChanged("RoundingTransferReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Bank.Biztalk.FXServices", ConfigurationName="FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchange" +
        "CashPortSoap")]
    public interface Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap {
        
        // CODEGEN: Generating message contract since element name ExchangeCashEngage from namespace http://Bank.Biztalk.FXServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FXServices/Bank_Biztalk_FXServices_orcProcessFXExchangeCash_R" +
            "eceiveFXExchangeCashPort/FXExchangeCash", ReplyAction="*")]
        ApexServices.FXExchangeCash.FXExchangeCashResponse1 FXExchangeCash(ApexServices.FXExchangeCash.FXExchangeCashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FXServices/Bank_Biztalk_FXServices_orcProcessFXExchangeCash_R" +
            "eceiveFXExchangeCashPort/FXExchangeCash", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.FXExchangeCash.FXExchangeCashResponse1> FXExchangeCashAsync(ApexServices.FXExchangeCash.FXExchangeCashRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXExchangeCashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXExchangeCash", Namespace="http://Bank.Biztalk.FXServices", Order=0)]
        public ApexServices.FXExchangeCash.FXExchangeCashRequestBody Body;
        
        public FXExchangeCashRequest() {
        }
        
        public FXExchangeCashRequest(ApexServices.FXExchangeCash.FXExchangeCashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FXServices")]
    public partial class FXExchangeCashRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FXExchangeCash.ExchangeCashEngage ExchangeCashEngage;
        
        public FXExchangeCashRequestBody() {
        }
        
        public FXExchangeCashRequestBody(ApexServices.FXExchangeCash.ExchangeCashEngage ExchangeCashEngage) {
            this.ExchangeCashEngage = ExchangeCashEngage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXExchangeCashResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXExchangeCashResponse", Namespace="http://Bank.Biztalk.FXServices", Order=0)]
        public ApexServices.FXExchangeCash.FXExchangeCashResponse1Body Body;
        
        public FXExchangeCashResponse1() {
        }
        
        public FXExchangeCashResponse1(ApexServices.FXExchangeCash.FXExchangeCashResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FXServices")]
    public partial class FXExchangeCashResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FXExchangeCash.FXExchangeCashResponse FXExchangeCashResponse;
        
        public FXExchangeCashResponse1Body() {
        }
        
        public FXExchangeCashResponse1Body(ApexServices.FXExchangeCash.FXExchangeCashResponse FXExchangeCashResponse) {
            this.FXExchangeCashResponse = FXExchangeCashResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapChannel : ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapClient : System.ServiceModel.ClientBase<ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap>, ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap {
        
        public Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapClient() {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.FXExchangeCash.FXExchangeCashResponse1 ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap.FXExchangeCash(ApexServices.FXExchangeCash.FXExchangeCashRequest request) {
            return base.Channel.FXExchangeCash(request);
        }
        
        public ApexServices.FXExchangeCash.FXExchangeCashResponse FXExchangeCash(ApexServices.FXExchangeCash.ExchangeCashEngage ExchangeCashEngage) {
            ApexServices.FXExchangeCash.FXExchangeCashRequest inValue = new ApexServices.FXExchangeCash.FXExchangeCashRequest();
            inValue.Body = new ApexServices.FXExchangeCash.FXExchangeCashRequestBody();
            inValue.Body.ExchangeCashEngage = ExchangeCashEngage;
            ApexServices.FXExchangeCash.FXExchangeCashResponse1 retVal = ((ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap)(this)).FXExchangeCash(inValue);
            return retVal.Body.FXExchangeCashResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.FXExchangeCash.FXExchangeCashResponse1> ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap.FXExchangeCashAsync(ApexServices.FXExchangeCash.FXExchangeCashRequest request) {
            return base.Channel.FXExchangeCashAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.FXExchangeCash.FXExchangeCashResponse1> FXExchangeCashAsync(ApexServices.FXExchangeCash.ExchangeCashEngage ExchangeCashEngage) {
            ApexServices.FXExchangeCash.FXExchangeCashRequest inValue = new ApexServices.FXExchangeCash.FXExchangeCashRequest();
            inValue.Body = new ApexServices.FXExchangeCash.FXExchangeCashRequestBody();
            inValue.Body.ExchangeCashEngage = ExchangeCashEngage;
            return ((ApexServices.FXExchangeCash.Bank_Biztalk_FXServices_orcProcessFXExchangeCash_ReceiveFXExchangeCashPortSoap)(this)).FXExchangeCashAsync(inValue);
        }
    }
}
