//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.CheckAuthentication {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://AlRayanBank.Services/", ConfigurationName="CheckAuthentication.AuthenticationCheckSoap")]
    public interface AuthenticationCheckSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://AlRayanBank.Services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://AlRayanBank.Services/HelloWorld", ReplyAction="*")]
        ApexServices.CheckAuthentication.HelloWorldResponse HelloWorld(ApexServices.CheckAuthentication.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AlRayanBank.Services/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.CheckAuthentication.HelloWorldResponse> HelloWorldAsync(ApexServices.CheckAuthentication.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name transactionId from namespace http://AlRayanBank.Services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://AlRayanBank.Services/CheckAuthentication", ReplyAction="*")]
        ApexServices.CheckAuthentication.CheckAuthenticationResponse CheckAuthentication(ApexServices.CheckAuthentication.CheckAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AlRayanBank.Services/CheckAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.CheckAuthentication.CheckAuthenticationResponse> CheckAuthenticationAsync(ApexServices.CheckAuthentication.CheckAuthenticationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://AlRayanBank.Services/", Order=0)]
        public ApexServices.CheckAuthentication.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ApexServices.CheckAuthentication.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://AlRayanBank.Services/", Order=0)]
        public ApexServices.CheckAuthentication.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ApexServices.CheckAuthentication.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://AlRayanBank.Services/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAuthentication", Namespace="http://AlRayanBank.Services/", Order=0)]
        public ApexServices.CheckAuthentication.CheckAuthenticationRequestBody Body;
        
        public CheckAuthenticationRequest() {
        }
        
        public CheckAuthenticationRequest(ApexServices.CheckAuthentication.CheckAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://AlRayanBank.Services/")]
    public partial class CheckAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transactionId;
        
        public CheckAuthenticationRequestBody() {
        }
        
        public CheckAuthenticationRequestBody(string transactionId) {
            this.transactionId = transactionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAuthenticationResponse", Namespace="http://AlRayanBank.Services/", Order=0)]
        public ApexServices.CheckAuthentication.CheckAuthenticationResponseBody Body;
        
        public CheckAuthenticationResponse() {
        }
        
        public CheckAuthenticationResponse(ApexServices.CheckAuthentication.CheckAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://AlRayanBank.Services/")]
    public partial class CheckAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckAuthenticationResult;
        
        public CheckAuthenticationResponseBody() {
        }
        
        public CheckAuthenticationResponseBody(bool CheckAuthenticationResult) {
            this.CheckAuthenticationResult = CheckAuthenticationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationCheckSoapChannel : ApexServices.CheckAuthentication.AuthenticationCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationCheckSoapClient : System.ServiceModel.ClientBase<ApexServices.CheckAuthentication.AuthenticationCheckSoap>, ApexServices.CheckAuthentication.AuthenticationCheckSoap {
        
        public AuthenticationCheckSoapClient() {
        }
        
        public AuthenticationCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.CheckAuthentication.HelloWorldResponse ApexServices.CheckAuthentication.AuthenticationCheckSoap.HelloWorld(ApexServices.CheckAuthentication.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ApexServices.CheckAuthentication.HelloWorldRequest inValue = new ApexServices.CheckAuthentication.HelloWorldRequest();
            inValue.Body = new ApexServices.CheckAuthentication.HelloWorldRequestBody();
            ApexServices.CheckAuthentication.HelloWorldResponse retVal = ((ApexServices.CheckAuthentication.AuthenticationCheckSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.CheckAuthentication.HelloWorldResponse> ApexServices.CheckAuthentication.AuthenticationCheckSoap.HelloWorldAsync(ApexServices.CheckAuthentication.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.CheckAuthentication.HelloWorldResponse> HelloWorldAsync() {
            ApexServices.CheckAuthentication.HelloWorldRequest inValue = new ApexServices.CheckAuthentication.HelloWorldRequest();
            inValue.Body = new ApexServices.CheckAuthentication.HelloWorldRequestBody();
            return ((ApexServices.CheckAuthentication.AuthenticationCheckSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.CheckAuthentication.CheckAuthenticationResponse ApexServices.CheckAuthentication.AuthenticationCheckSoap.CheckAuthentication(ApexServices.CheckAuthentication.CheckAuthenticationRequest request) {
            return base.Channel.CheckAuthentication(request);
        }
        
        public bool CheckAuthentication(string transactionId) {
            ApexServices.CheckAuthentication.CheckAuthenticationRequest inValue = new ApexServices.CheckAuthentication.CheckAuthenticationRequest();
            inValue.Body = new ApexServices.CheckAuthentication.CheckAuthenticationRequestBody();
            inValue.Body.transactionId = transactionId;
            ApexServices.CheckAuthentication.CheckAuthenticationResponse retVal = ((ApexServices.CheckAuthentication.AuthenticationCheckSoap)(this)).CheckAuthentication(inValue);
            return retVal.Body.CheckAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.CheckAuthentication.CheckAuthenticationResponse> ApexServices.CheckAuthentication.AuthenticationCheckSoap.CheckAuthenticationAsync(ApexServices.CheckAuthentication.CheckAuthenticationRequest request) {
            return base.Channel.CheckAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.CheckAuthentication.CheckAuthenticationResponse> CheckAuthenticationAsync(string transactionId) {
            ApexServices.CheckAuthentication.CheckAuthenticationRequest inValue = new ApexServices.CheckAuthentication.CheckAuthenticationRequest();
            inValue.Body = new ApexServices.CheckAuthentication.CheckAuthenticationRequestBody();
            inValue.Body.transactionId = transactionId;
            return ((ApexServices.CheckAuthentication.AuthenticationCheckSoap)(this)).CheckAuthenticationAsync(inValue);
        }
    }
}
