//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.FXCashWithdrawal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FXCashWithdrawalEngage", Namespace="http://Bank.Biztalk.FXServices")]
    [System.SerializableAttribute()]
    public partial class FXCashWithdrawalEngage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WithdrawalCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WithdrawalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNarrativeLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditSystemParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBSUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverrideUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WithdrawalCurrency {
            get {
                return this.WithdrawalCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.WithdrawalCurrencyField, value) != true)) {
                    this.WithdrawalCurrencyField = value;
                    this.RaisePropertyChanged("WithdrawalCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExchangeCurrency {
            get {
                return this.ExchangeCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeCurrencyField, value) != true)) {
                    this.ExchangeCurrencyField = value;
                    this.RaisePropertyChanged("ExchangeCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WithdrawalAmount {
            get {
                return this.WithdrawalAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.WithdrawalAmountField, value) != true)) {
                    this.WithdrawalAmountField = value;
                    this.RaisePropertyChanged("WithdrawalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExchangeAmount {
            get {
                return this.ExchangeAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeAmountField, value) != true)) {
                    this.ExchangeAmountField = value;
                    this.RaisePropertyChanged("ExchangeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeRateField, value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ValueDate {
            get {
                return this.ValueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueDateField, value) != true)) {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TransactionNarrativeLine1 {
            get {
                return this.TransactionNarrativeLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine1Field, value) != true)) {
                    this.TransactionNarrativeLine1Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TransactionNarrativeLine2 {
            get {
                return this.TransactionNarrativeLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine2Field, value) != true)) {
                    this.TransactionNarrativeLine2Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TransactionNarrativeLine3 {
            get {
                return this.TransactionNarrativeLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine3Field, value) != true)) {
                    this.TransactionNarrativeLine3Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TransactionNarrativeLine4 {
            get {
                return this.TransactionNarrativeLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNarrativeLine4Field, value) != true)) {
                    this.TransactionNarrativeLine4Field = value;
                    this.RaisePropertyChanged("TransactionNarrativeLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DebitSystemParameter {
            get {
                return this.DebitSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitSystemParameterField, value) != true)) {
                    this.DebitSystemParameterField = value;
                    this.RaisePropertyChanged("DebitSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CreditSystemParameter {
            get {
                return this.CreditSystemParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditSystemParameterField, value) != true)) {
                    this.CreditSystemParameterField = value;
                    this.RaisePropertyChanged("CreditSystemParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string EBSUserID {
            get {
                return this.EBSUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EBSUserIDField, value) != true)) {
                    this.EBSUserIDField = value;
                    this.RaisePropertyChanged("EBSUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string OverrideUser {
            get {
                return this.OverrideUserField;
            }
            set {
                if ((object.ReferenceEquals(this.OverrideUserField, value) != true)) {
                    this.OverrideUserField = value;
                    this.RaisePropertyChanged("OverrideUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string DebitAccountNumber {
            get {
                return this.DebitAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitAccountNumberField, value) != true)) {
                    this.DebitAccountNumberField = value;
                    this.RaisePropertyChanged("DebitAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CreditAccountNumber {
            get {
                return this.CreditAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditAccountNumberField, value) != true)) {
                    this.CreditAccountNumberField = value;
                    this.RaisePropertyChanged("CreditAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Spare1 {
            get {
                return this.Spare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare1Field, value) != true)) {
                    this.Spare1Field = value;
                    this.RaisePropertyChanged("Spare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Spare2 {
            get {
                return this.Spare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare2Field, value) != true)) {
                    this.Spare2Field = value;
                    this.RaisePropertyChanged("Spare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Spare3 {
            get {
                return this.Spare3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare3Field, value) != true)) {
                    this.Spare3Field = value;
                    this.RaisePropertyChanged("Spare3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Spare4 {
            get {
                return this.Spare4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare4Field, value) != true)) {
                    this.Spare4Field = value;
                    this.RaisePropertyChanged("Spare4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Spare5 {
            get {
                return this.Spare5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare5Field, value) != true)) {
                    this.Spare5Field = value;
                    this.RaisePropertyChanged("Spare5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FXCashWithdrawalResponse", Namespace="http://Bank.Biztalk.FXServices")]
    [System.SerializableAttribute()]
    public partial class FXCashWithdrawalResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseText {
            get {
                return this.ResponseTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseTextField, value) != true)) {
                    this.ResponseTextField = value;
                    this.RaisePropertyChanged("ResponseText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Bank.Biztalk.FXServices", ConfigurationName="FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCash" +
        "WithdrawalPortSoap")]
    public interface Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap {
        
        // CODEGEN: Generating message contract since element name FXCashWithdrawalEngage from namespace http://Bank.Biztalk.FXServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FXServices/Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal" +
            "_ReceiveFXCashWithdrawalPort/FXCashWithdrawal", ReplyAction="*")]
        ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1 FXCashWithdrawal(ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FXServices/Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal" +
            "_ReceiveFXCashWithdrawalPort/FXCashWithdrawal", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1> FXCashWithdrawalAsync(ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXCashWithdrawalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXCashWithdrawal", Namespace="http://Bank.Biztalk.FXServices", Order=0)]
        public ApexServices.FXCashWithdrawal.FXCashWithdrawalRequestBody Body;
        
        public FXCashWithdrawalRequest() {
        }
        
        public FXCashWithdrawalRequest(ApexServices.FXCashWithdrawal.FXCashWithdrawalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FXServices")]
    public partial class FXCashWithdrawalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FXCashWithdrawal.FXCashWithdrawalEngage FXCashWithdrawalEngage;
        
        public FXCashWithdrawalRequestBody() {
        }
        
        public FXCashWithdrawalRequestBody(ApexServices.FXCashWithdrawal.FXCashWithdrawalEngage FXCashWithdrawalEngage) {
            this.FXCashWithdrawalEngage = FXCashWithdrawalEngage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXCashWithdrawalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXCashWithdrawalResponse", Namespace="http://Bank.Biztalk.FXServices", Order=0)]
        public ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1Body Body;
        
        public FXCashWithdrawalResponse1() {
        }
        
        public FXCashWithdrawalResponse1(ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FXServices")]
    public partial class FXCashWithdrawalResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse FXCashWithdrawalResponse;
        
        public FXCashWithdrawalResponse1Body() {
        }
        
        public FXCashWithdrawalResponse1Body(ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse FXCashWithdrawalResponse) {
            this.FXCashWithdrawalResponse = FXCashWithdrawalResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapChannel : ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapClient : System.ServiceModel.ClientBase<ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap>, ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap {
        
        public Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapClient() {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1 ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap.FXCashWithdrawal(ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest request) {
            return base.Channel.FXCashWithdrawal(request);
        }
        
        public ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse FXCashWithdrawal(ApexServices.FXCashWithdrawal.FXCashWithdrawalEngage FXCashWithdrawalEngage) {
            ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest inValue = new ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest();
            inValue.Body = new ApexServices.FXCashWithdrawal.FXCashWithdrawalRequestBody();
            inValue.Body.FXCashWithdrawalEngage = FXCashWithdrawalEngage;
            ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1 retVal = ((ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap)(this)).FXCashWithdrawal(inValue);
            return retVal.Body.FXCashWithdrawalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1> ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap.FXCashWithdrawalAsync(ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest request) {
            return base.Channel.FXCashWithdrawalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.FXCashWithdrawal.FXCashWithdrawalResponse1> FXCashWithdrawalAsync(ApexServices.FXCashWithdrawal.FXCashWithdrawalEngage FXCashWithdrawalEngage) {
            ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest inValue = new ApexServices.FXCashWithdrawal.FXCashWithdrawalRequest();
            inValue.Body = new ApexServices.FXCashWithdrawal.FXCashWithdrawalRequestBody();
            inValue.Body.FXCashWithdrawalEngage = FXCashWithdrawalEngage;
            return ((ApexServices.FXCashWithdrawal.Bank_Biztalk_FXServices_orcProcessFXCashWithdrawal_ReceiveFXCashWithdrawalPortSoap)(this)).FXCashWithdrawalAsync(inValue);
        }
    }
}
