//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.svcDataWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="innerMessage", Namespace="http://www.islamic-bank.com/GetCustomerImages")]
    [System.SerializableAttribute()]
    public partial class innerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomerImagesResult", Namespace="http://ImagesSchemaResponse.ImagesResponse")]
    [System.SerializableAttribute()]
    public partial class GetCustomerImagesResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MessageDate {
            get {
                return this.MessageDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDateField, value) != true)) {
                    this.MessageDateField = value;
                    this.RaisePropertyChanged("MessageDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.islamic-bank.com/DataWebService", ConfigurationName="svcDataWebservice.DataWebServiceSoap")]
    public interface DataWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name innerMessage from namespace http://www.islamic-bank.com/GetCustomerImages is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.islamic-bank.com/DataWebService/GetCustomerImages", ReplyAction="*")]
        ApexServices.svcDataWebservice.GetCustomerImagesResponse GetCustomerImages(ApexServices.svcDataWebservice.GetCustomerImagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.islamic-bank.com/DataWebService/GetCustomerImages", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.svcDataWebservice.GetCustomerImagesResponse> GetCustomerImagesAsync(ApexServices.svcDataWebservice.GetCustomerImagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerImagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerImages", Namespace="http://www.islamic-bank.com/DataWebService", Order=0)]
        public ApexServices.svcDataWebservice.GetCustomerImagesRequestBody Body;
        
        public GetCustomerImagesRequest() {
        }
        
        public GetCustomerImagesRequest(ApexServices.svcDataWebservice.GetCustomerImagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.islamic-bank.com/GetCustomerImages")]
    public partial class GetCustomerImagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.svcDataWebservice.innerMessage innerMessage;
        
        public GetCustomerImagesRequestBody() {
        }
        
        public GetCustomerImagesRequestBody(ApexServices.svcDataWebservice.innerMessage innerMessage) {
            this.innerMessage = innerMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerImagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerImagesResponse", Namespace="http://www.islamic-bank.com/DataWebService", Order=0)]
        public ApexServices.svcDataWebservice.GetCustomerImagesResponseBody Body;
        
        public GetCustomerImagesResponse() {
        }
        
        public GetCustomerImagesResponse(ApexServices.svcDataWebservice.GetCustomerImagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ImagesSchemaResponse.ImagesResponse")]
    public partial class GetCustomerImagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.svcDataWebservice.GetCustomerImagesResult GetCustomerImagesResult;
        
        public GetCustomerImagesResponseBody() {
        }
        
        public GetCustomerImagesResponseBody(ApexServices.svcDataWebservice.GetCustomerImagesResult GetCustomerImagesResult) {
            this.GetCustomerImagesResult = GetCustomerImagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataWebServiceSoapChannel : ApexServices.svcDataWebservice.DataWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataWebServiceSoapClient : System.ServiceModel.ClientBase<ApexServices.svcDataWebservice.DataWebServiceSoap>, ApexServices.svcDataWebservice.DataWebServiceSoap {
        
        public DataWebServiceSoapClient() {
        }
        
        public DataWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.svcDataWebservice.GetCustomerImagesResponse ApexServices.svcDataWebservice.DataWebServiceSoap.GetCustomerImages(ApexServices.svcDataWebservice.GetCustomerImagesRequest request) {
            return base.Channel.GetCustomerImages(request);
        }
        
        public ApexServices.svcDataWebservice.GetCustomerImagesResult GetCustomerImages(ApexServices.svcDataWebservice.innerMessage innerMessage) {
            ApexServices.svcDataWebservice.GetCustomerImagesRequest inValue = new ApexServices.svcDataWebservice.GetCustomerImagesRequest();
            inValue.Body = new ApexServices.svcDataWebservice.GetCustomerImagesRequestBody();
            inValue.Body.innerMessage = innerMessage;
            ApexServices.svcDataWebservice.GetCustomerImagesResponse retVal = ((ApexServices.svcDataWebservice.DataWebServiceSoap)(this)).GetCustomerImages(inValue);
            return retVal.Body.GetCustomerImagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.svcDataWebservice.GetCustomerImagesResponse> ApexServices.svcDataWebservice.DataWebServiceSoap.GetCustomerImagesAsync(ApexServices.svcDataWebservice.GetCustomerImagesRequest request) {
            return base.Channel.GetCustomerImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.svcDataWebservice.GetCustomerImagesResponse> GetCustomerImagesAsync(ApexServices.svcDataWebservice.innerMessage innerMessage) {
            ApexServices.svcDataWebservice.GetCustomerImagesRequest inValue = new ApexServices.svcDataWebservice.GetCustomerImagesRequest();
            inValue.Body = new ApexServices.svcDataWebservice.GetCustomerImagesRequestBody();
            inValue.Body.innerMessage = innerMessage;
            return ((ApexServices.svcDataWebservice.DataWebServiceSoap)(this)).GetCustomerImagesAsync(inValue);
        }
    }
}
