//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexServices.FTVInformation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTVRequest", Namespace="http://Bank.Biztalk.FTVInformation")]
    [System.SerializableAttribute()]
    public partial class FTVRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceID {
            get {
                return this.SourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIDField, value) != true)) {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTVResponse", Namespace="http://Bank.Biztalk.FTVInformation")]
    [System.SerializableAttribute()]
    public partial class FTVResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iAcctNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iCurrentValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iFTVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemainingTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentRepaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Spare5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string iAcctNo {
            get {
                return this.iAcctNoField;
            }
            set {
                if ((object.ReferenceEquals(this.iAcctNoField, value) != true)) {
                    this.iAcctNoField = value;
                    this.RaisePropertyChanged("iAcctNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string iCurrentValue {
            get {
                return this.iCurrentValueField;
            }
            set {
                if ((object.ReferenceEquals(this.iCurrentValueField, value) != true)) {
                    this.iCurrentValueField = value;
                    this.RaisePropertyChanged("iCurrentValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string iFTV {
            get {
                return this.iFTVField;
            }
            set {
                if ((object.ReferenceEquals(this.iFTVField, value) != true)) {
                    this.iFTVField = value;
                    this.RaisePropertyChanged("iFTV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RemainingTerm {
            get {
                return this.RemainingTermField;
            }
            set {
                if ((object.ReferenceEquals(this.RemainingTermField, value) != true)) {
                    this.RemainingTermField = value;
                    this.RaisePropertyChanged("RemainingTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CurrentRepayment {
            get {
                return this.CurrentRepaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentRepaymentField, value) != true)) {
                    this.CurrentRepaymentField = value;
                    this.RaisePropertyChanged("CurrentRepayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Spare1 {
            get {
                return this.Spare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare1Field, value) != true)) {
                    this.Spare1Field = value;
                    this.RaisePropertyChanged("Spare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Spare2 {
            get {
                return this.Spare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare2Field, value) != true)) {
                    this.Spare2Field = value;
                    this.RaisePropertyChanged("Spare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Spare3 {
            get {
                return this.Spare3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare3Field, value) != true)) {
                    this.Spare3Field = value;
                    this.RaisePropertyChanged("Spare3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Spare4 {
            get {
                return this.Spare4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare4Field, value) != true)) {
                    this.Spare4Field = value;
                    this.RaisePropertyChanged("Spare4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Spare5 {
            get {
                return this.Spare5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Spare5Field, value) != true)) {
                    this.Spare5Field = value;
                    this.RaisePropertyChanged("Spare5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Bank.Biztalk.FTVInformation", ConfigurationName="FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap")]
    public interface Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap {
        
        // CODEGEN: Generating message contract since element name FTVRequest from namespace http://Bank.Biztalk.FTVInformation is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FTVInformation/Bank_Biztalk_FTVInformation_orcProcessFTV_Rece" +
            "iveFTVPort/FTV", ReplyAction="*")]
        ApexServices.FTVInformation.FTVResponse1 FTV(ApexServices.FTVInformation.FTVRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Bank.Biztalk.FTVInformation/Bank_Biztalk_FTVInformation_orcProcessFTV_Rece" +
            "iveFTVPort/FTV", ReplyAction="*")]
        System.Threading.Tasks.Task<ApexServices.FTVInformation.FTVResponse1> FTVAsync(ApexServices.FTVInformation.FTVRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FTVRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FTV", Namespace="http://Bank.Biztalk.FTVInformation", Order=0)]
        public ApexServices.FTVInformation.FTVRequest1Body Body;
        
        public FTVRequest1() {
        }
        
        public FTVRequest1(ApexServices.FTVInformation.FTVRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FTVInformation")]
    public partial class FTVRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FTVInformation.FTVRequest FTVRequest;
        
        public FTVRequest1Body() {
        }
        
        public FTVRequest1Body(ApexServices.FTVInformation.FTVRequest FTVRequest) {
            this.FTVRequest = FTVRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FTVResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FTVResponse", Namespace="http://Bank.Biztalk.FTVInformation", Order=0)]
        public ApexServices.FTVInformation.FTVResponse1Body Body;
        
        public FTVResponse1() {
        }
        
        public FTVResponse1(ApexServices.FTVInformation.FTVResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Bank.Biztalk.FTVInformation")]
    public partial class FTVResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApexServices.FTVInformation.FTVResponse FTVResponse;
        
        public FTVResponse1Body() {
        }
        
        public FTVResponse1Body(ApexServices.FTVInformation.FTVResponse FTVResponse) {
            this.FTVResponse = FTVResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapChannel : ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapClient : System.ServiceModel.ClientBase<ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap>, ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap {
        
        public Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapClient() {
        }
        
        public Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApexServices.FTVInformation.FTVResponse1 ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap.FTV(ApexServices.FTVInformation.FTVRequest1 request) {
            return base.Channel.FTV(request);
        }
        
        public ApexServices.FTVInformation.FTVResponse FTV(ApexServices.FTVInformation.FTVRequest FTVRequest) {
            ApexServices.FTVInformation.FTVRequest1 inValue = new ApexServices.FTVInformation.FTVRequest1();
            inValue.Body = new ApexServices.FTVInformation.FTVRequest1Body();
            inValue.Body.FTVRequest = FTVRequest;
            ApexServices.FTVInformation.FTVResponse1 retVal = ((ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap)(this)).FTV(inValue);
            return retVal.Body.FTVResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApexServices.FTVInformation.FTVResponse1> ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap.FTVAsync(ApexServices.FTVInformation.FTVRequest1 request) {
            return base.Channel.FTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApexServices.FTVInformation.FTVResponse1> FTVAsync(ApexServices.FTVInformation.FTVRequest FTVRequest) {
            ApexServices.FTVInformation.FTVRequest1 inValue = new ApexServices.FTVInformation.FTVRequest1();
            inValue.Body = new ApexServices.FTVInformation.FTVRequest1Body();
            inValue.Body.FTVRequest = FTVRequest;
            return ((ApexServices.FTVInformation.Bank_Biztalk_FTVInformation_orcProcessFTV_ReceiveFTVPortSoap)(this)).FTVAsync(inValue);
        }
    }
}
